app:
  name: passport_ai
  version: 1.0.0
  port: 3000
  host: 0.0.0.0
  log_level: INFO

slack:
  mode: socket
  bot_token: 'test'
  app_token: 'test'
  signing_secret: 'test'

chat:
  provider: openai
  model: gpt-4o-mini
  temperature: 0.0
  api_key: 'test'