app:
  name: passport_ai
  version: 1.0.0
  port: 3000
  host: 0.0.0.0
  log_level: INFO

slack:
  mode: socket
  bot_token: 'test'
  app_token: 'test'
  signing_secret: 'test'

langsmith:
  tracing: true
  api_key: 'test'

llm:
  provider: openai
  model: gpt-4o-mini
  temperature: 0.0
  embeddings_model: "text-embedding-3-large"
  api_key: 'test'

knowledge_base:
  persist_directory: "data/knowledge_base"
  host: "https://assetiq.atlassian.net"
  username: "assetiq-user@useassetiq.com"
  api_token: "test"
  space_key: "PROPWISE"
  batch_size: 100